[tool.black]
line-length = 88
target-version = ['py312']  # Adjust to your Python version
include = '\.pyi?$'

[tool.isort]
profile = "black"          # Makes isort compatible with Black
line_length = 88
multi_line_output = 3
include_trailing_comma = true
