name: CI

on:
  push:
    branches: ["main"]
  workflow_dispatch:


jobs:
  test:
    runs-on: ubuntu-latest
    env:
      ENVIRONMENT: 'test'
      ACCESS_TOKEN_EXPIRE_MINUTES: 30
      REFRESH_TOKEN_EXPIRE_DAYS: 7
      SECRET_KEY: ${{secrets.TEST_SECRET_KEY}}
      DATABASE_URL: ${{secrets.TEST_DATABASE_URL}}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run all tests
        run: |
          pytest tests/ -v
    






